import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export const styles = StyleSheet.create({
  bg: { flex: 1, width: "100%", height: "100%" },
  tint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(20, 28, 14, 0.45)",
  },
  safe: { flex: 1, alignItems: "center", paddingBottom: 24 },

  header: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
  },
  scanLabel: {
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 5,
    color: COLORS.bone,
    textShadowColor: "rgba(0,0,0,0.6)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },

  card: {
    backgroundColor: COLORS.cafeNoir,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "space-evenly",
    paddingBottom: 32,
    paddingHorizontal: 28,
    paddingTop: 44,
    marginTop: 44,
    marginHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 18,
  },
  cameraCircle: {
    position: "absolute",
    top: -34,
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: COLORS.kombuGreen,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: COLORS.cafeNoir,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 10,
  },
  cameraBox: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  scanLineBar: {
    position: "absolute",
    height: 2,
    backgroundColor: COLORS.mossGreen,
    opacity: 0.75,
    alignSelf: "center",
    borderRadius: 2,
    shadowColor: COLORS.mossGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
  },
  permBtn: { padding: 16, alignItems: "center" },
  permText: {
    color: COLORS.tan,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  instruction: {
    color: COLORS.bone,
    fontSize: 13.5,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 20,
    opacity: 0.50,
    letterSpacing: 0.2,
    transform: [{ translateY: 20 }],
  },
  rescanBtn: {
    marginTop: 18,
    paddingVertical: 10,
    paddingHorizontal: 36,
    backgroundColor: COLORS.mossGreen,
    borderRadius: 30,
  },
  rescanText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1,
  },
});