import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.mossGreen },
  container: { flex: 1 },
  backgroundImg: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
  },
  spacer: { height: 280 },
  card: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.06)",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 20,
  },
  input: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    color: COLORS.darkBg,
  },
  passwordContainer: { position: "relative", marginBottom: 12 },
  passwordInput: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    paddingRight: 50,
    color: COLORS.darkBg,
  },
  eyeIcon: {
    position: "absolute",
    right: 14,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  eyeEmoji: { fontSize: 20 },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  checkboxRow: { flexDirection: "row", alignItems: "center" },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 2,
    borderColor: COLORS.cafeNoir, 
    borderRadius: 3,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
  },
  checkboxChecked: { width: 10, height: 10, backgroundColor: COLORS.cafeNoir, borderRadius: 1 },
  rememberText: { fontSize: 15, fontWeight: 'bold', color: COLORS.cafeNoir, opacity: 0.8 },
  small: { fontSize: 15, color: COLORS.darkBg, opacity: 0.8 }, 
  link: { color: COLORS.cafeNoir, fontWeight: "700" },
  primaryBtn: { backgroundColor: COLORS.cafeNoir, paddingVertical: 14, borderRadius: 10, alignItems: "center", marginTop: 2 },
  primaryBtnText: { color: COLORS.white, fontWeight: "800", letterSpacing: 1 },
  orText: { textAlign: "center", marginVertical: 12, fontSize: 12, opacity: 0.6, color: COLORS.darkBg },
  socialRow: { flexDirection: "row", gap: 12 },
  socialBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.white, flexDirection: "row", gap: 8 },
  google: { opacity: 0.95 },
  facebook: { opacity: 0.95 },
  socialLogo: { width: 20, height: 20 },
  socialText: { fontWeight: "700", opacity: 0.75, color: COLORS.darkBg },
  bottomRow: { marginTop: 14, flexDirection: "row", justifyContent: "center", alignItems: "center" },
});